name: Test and Build

on:
  push:
    branches:
      - '**'  # Reagiert auf alle Branches
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Reagiert nur auf semver-Tags
jobs:
  ci:
    name: Run CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, json, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Static Code Analysis
        run: composer ci:static

  build:
    if: startsWith(github.ref, 'refs/tags/')
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, json, intl, simplexml
          tools: composer, box

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Compile PHAR file
        run: |
          box compile

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: autodns.phar
          path: autodns.phar

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref_name }}
#          release_name: "Release ${{ github.ref_name }}"
#          draft: false
#          prerelease: false
#
#      - name: Upload PHAR to Release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./autodns.phar
#          asset_name: autodns.phar
#          asset_content_type: application/octet-stream
